name: Roulette
version: '${project.version}'
main: me.matsubara.roulette.RoulettePlugin
api-version: 1.13
author: Matsubara
description: '${project.description}'
depend:
  - ProtocolLib
  - Vault
softdepend:
  - Essentials
  - PlaceholderAPI
  - ViaVersion
  - Multiverse-Core

commands:
  roulette:
    description: main command.
    usage: /<command>